// Generated by CoffeeScript 1.7.1
(function() {
  var index;

  index = require("./index");

  index.then(function(data) {
    return console.log(JSON.stringify(data));
  });

}).call(this);

//# sourceMappingURL=rec.map
