// Generated by CoffeeScript 1.7.1
(function() {
  var fs, rev;

  rev = require("./index");

  fs = require("fs");

  rev.then(function(data) {
    var d, desktopEntry, filename, html, obj, template, _i, _len;
    html = "";
    for (_i = 0, _len = data.length; _i < _len; _i++) {
      d = data[_i];
      filename = Object.keys(d)[0];
      desktopEntry = d[filename]["Desktop Entry"];
      obj = {
        "filename": Object.keys(d)[0],
        "Type": desktopEntry["Type"],
        "Exec": desktopEntry["Exec"],
        "Icon": desktopEntry["Icon"],
        "Categories": desktopEntry["Categories"]
      };
      template = "\n      <h1>filename:" + obj.filename + "</h1>\n      <h2>Type:" + obj.Type + "</h2>\n      <h3>Icon:" + obj.Icon + "</h3>\n      <img src=\"file:///localhost/usr/share/pixmaps/" + obj.Icon + ".png\" alt=\"\"/>\n      <h4>Categories:" + obj.Categories + "</h4>\n    ";
      html += template;
    }
    return fs.writeFile("test.html", html, function(err) {
      if (err) {
        throw err;
      }
    });
  });

}).call(this);

//# sourceMappingURL=test.map
